package com.ayor.type;

import java.util.Arrays;

public enum PermissionType {
    MANAGE_ROLE("MANAGE_ROLE"),
    MANAGE_PERMISSION("MANAGE_PERMISSION"),
    ASSIGN_ROLE("ASSIGN_ROLE"),
    REVOKE_ROLE("REVOKE_ROLE"),

    MANAGE_ACCOUNT("MANAGE_ACCOUNT"),
    UPDATE_ACCOUNT("UPDATE_ACCOUNT"),
    DELETE_ACCOUNT("DELETE_ACCOUNT"),
    MUTE_ACCOUNT("MUTE_ACCOUNT"),
    BAN_ACCOUNT("BAN_ACCOUNT"),
    RESTORE_ACCOUNT("RESTORE_ACCOUNT"),
    HANDLE_USER_VIOLATION("HANDLE_USER_VIOLATION"),

    CREATE_THEME("CREATE_THEME"),
    UPDATE_THEME("UPDATE_THEME"),
    DELETE_THEME("DELETE_THEME"),
    CREATE_TOPIC("CREATE_TOPIC"),
    UPDATE_TOPIC("UPDATE_TOPIC"),
    DELETE_TOPIC("DELETE_TOPIC"),

    INSERT_TAG("INSERT_TAG"),
    UPDATE_TAG("UPDATE_TAG"),
    DELETE_TAG("DELETE_TAG"),
    UPDATE_THREAD_TAG("UPDATE_THREAD_TAG"),
    SET_ANNOUNCEMENT("SET_ANNOUNCEMENT"),
    DELETE_THREAD("DELETE_THREAD"),
    DELETE_POST("DELETE_POST"),
    SET_THREAD_SELECTED("SET_THREAD_SELECTED"),

    HANDLE_REPORT("HANDLE_REPORT"),
    VIEW_REPORT("VIEW_REPORT"),
    MODERATE_CONTENT("MODERATE_CONTENT"),

    MANAGE_IMAGE_ASSET("MANAGE_IMAGE_ASSET"),
    MANAGE_USER_BROADCAST("MANAGE_USER_BROADCAST"),
    MANAGE_PAGE_BROADCAST("MANAGE_PAGE_BROADCAST"),
    MANAGE_TOPIC_CHAT("MANAGE_TOPIC_CHAT"),

    VIEW_DASHBOARD("VIEW_DASHBOARD"),
    MANAGE_STAT("MANAGE_STAT"),
    REPAIR_DATA("REPAIR_DATA"),

    MANAGE_CONVERSATION("MANAGE_CONVERSATION"),
    MANAGE_CONVERSATION_MESSAGE("MANAGE_CONVERSATION_MESSAGE"),
    MANAGE_COLLECT("MANAGE_COLLECT"),
    MANAGE_LIKE("MANAGE_LIKE"),
    MANAGE_HISTORY("MANAGE_HISTORY");

    private final String dbValue;

    PermissionType(String dbValue) {
        this.dbValue = dbValue;
    }

    public String dbValue() {
        return dbValue;
    }

    public static boolean isKnown(String permission) {
        return Arrays.stream(values())
                .anyMatch(permissionType -> permissionType.dbValue.equals(permission));
    }
}
